// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BboxPt } from "./BboxPt";

/**
 * 版面块：OCR 检出的一个区域及其原文/译文。
 * label 为 PP-DocLayoutV3 标签（text/title/list/figure/figure_caption/table/formula/header/footer），
 * 保留 string 通道以兼容后续新增标签，故不用 enum。
 */
export type Block = { id: string, label: string, bboxPt: BboxPt, score: number, 
/**
 * markdown 原文：正文纯文本 / 公式 $$..$$ / 表格 markdown；figure 块为 None
 */
source: string | null, 
/**
 * markdown 译文；figure/formula 块为 None（formula 原样渲染），未译为 None
 */
translation: string | null, };
