// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookMeta } from "./BookMeta";
import type { PageInfo } from "./PageInfo";

/**
 * 一本书的完整实体（= 书目录里 <书名>.json 的形状）。
 * id 前端会归一化为索引键 belong/name；bind = 结构 JSON 的仓库相对路径，None = 未解析。
 */
export type Book = { id: string, name: string, pdfPath: string, jsonPath: string, bind: string | null, meta: BookMeta, pages: Array<PageInfo>, };
