// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookMeta = { name: string, pageCount: number, createdAt: string, updatedAt: string, targetLang: string, ocrEngine: string, llmModel: string, };
