// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFailure } from "./ImportFailure";
import type { PDFStruct } from "./PDFStruct";

export type ImportOutcome = { imported: Array<PDFStruct>, failed: Array<ImportFailure>, 
/**
 * Imported but page count unreadable (encrypted/damaged): pages is an empty skeleton.
 */
warnings: Array<ImportFailure>, };
