// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multi-file import result: best-effort — successes plus per-file failure reasons.
 */
export type ImportFailure = { path: string, reason: string, };
