// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFailure } from "./ImportFailure";
import type { PDFStruct } from "./PDFStruct";

export type ImportOutcome = { imported: Array<PDFStruct>, failed: Array<ImportFailure>, 
/**
 * 导入成功但页数解析失败（加密/损坏 PDF）：pages 为空骨架，通知前端
 */
warnings: Array<ImportFailure>, };
