// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 多文件导入结果：best-effort——成功条目与逐文件失败原因一并返回
 */
export type ImportFailure = { path: string, reason: string, };
