// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Install progress event (ocr://install): phase name + estimated percent.
 */
export type InstallProgress = { phase: string, percent: number, };
