// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 安装进度事件（ocr://install）：阶段名 + 估算百分比（按钮旁进度条）
 */
export type InstallProgress = { phase: string, percent: number, };
