// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verification report (shown in the LLM pane and written back as the thinkingOff strategy).
 */
export type LlmVerifyReport = { 
/**
 * Effective strategy; "none" = write nothing (unneeded or impossible, see thinking_on).
 */
strategy: string, 
/**
 * Preset marks a non-reasoning model (thinking_on is always false then).
 */
presetNoThinking: boolean, 
/**
 * The probe still produced reasoning: cannot be disabled (frontend toasts a warning).
 */
thinkingOn: boolean, message: string, };
