// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 验证报告（设置页 LLM 面板展示 + 回写 thinkingOff 策略）
 */
export type LlmVerifyReport = { 
/**
 * 生效策略："none" = 不写任何关思考参数（要么探测发现不需要、要么都关不掉，
 * 靠 [`Self::thinking_on`] 区分）
 */
strategy: string, 
/**
 * 预设标记为非思考模型（此时 thinking_on 恒为 false）
 */
presetNoThinking: boolean, 
/**
 * 探测请求里仍有思考内容：关不掉（前端据此 toast 警告）
 */
thinkingOn: boolean, 
/**
 * 展示文案（含耗时与策略说明）
 */
message: string, };
