// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One requested page: the index (1-based, matching the bound JSON) and the viewer's page size in pt.
 */
export type MistralPageInput = { index: number, sizePt: [number, number], };
