// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuInfo } from "./GpuInfo";
import type { OcrModels } from "./OcrModels";

/**
 * Layered env report (source for the OCR settings status lights); Rust owns it and pushes it whole.
 */
export type OcrEnvReport = { python: string | null, pythonPath: string | null, deps: { [key in string]: string | null }, missing: Array<string>, torchBuild: string | null, gpu: GpuInfo | null, models: OcrModels | null, error: string | null, };
