// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";
import type { PageStatus } from "./PageStatus";

export type PageInfo = { index: number, status: PageStatus, widthPt: number, heightPt: number, blocks: Array<Block>, };
