// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * 页：index 从 1 起（与绑定 JSON 一致）；finished 标记该页是否完成处理
 */
export type PageInfo = { index: number, finished: boolean, blocks: Array<Block>, };
