// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 页解析状态机：pending → ocr_queued → ocr_done → translating → done / failed
 */
export type PageStatus = "pending" | "ocr_queued" | "ocr_done" | "translating" | "done" | "failed";
