// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * 1-based page; finished = OCR done, translated = LLM pass done (older JSONs default false → re-translated).
 */
export type PageInfo = { index: number, finished: boolean, translated: boolean, blocks: Array<Block>, };
