// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PDFStatus } from "./PDFStatus";
import type { PageInfo } from "./PageInfo";

/**
 * parse_pdf result: status summary + the pages actually updated.
 */
export type ParseOutcome = { bookStatus: PDFStatus, updatedPages: Array<PageInfo>, };
