// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PDFStatus } from "./PDFStatus";
import type { PageInfo } from "./PageInfo";

/**
 * parse_pdf 返回：进度摘要 + 本批实际更新的页
 */
export type ParseOutcome = { bookStatus: PDFStatus, updatedPages: Array<PageInfo>, };
