// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PDFStatus } from "./PDFStatus";
import type { PageInfo } from "./PageInfo";

export type ParseOutcome = { bookStatus: PDFStatus, updatedPages: Array<PageInfo>, };
