// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remote parse-service handshake result (the "Test" button and per-request batch negotiation).
 * `max_batch_pages` comes from the server (PROTOCOL.md §4), clamped to 1..=32.
 */
export type ParseServiceHealth = { 
/**
 * u32 not u64: ts-rs maps u64 to bigint, and the frontend only displays this.
 */
pid: number | null, 
/**
 * Server-allowed max pages per batch.
 */
maxBatchPages: number, 
/**
 * This probe's elapsed time (ms).
 */
elapsedMs: number, };
