// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * parse_pdf 批次输入页（前端离屏渲染产物；index 1-based，与绑定 JSON 对齐）
 */
export type ParsePageInput = { index: number, imageB64: string, scale: number, };
