// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One parse_pdf input page (frontend offscreen render); index is 1-based, matching the bound JSON.
 */
export type ParsePageInput = { index: number, imageB64: string, scale: number, };
