// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Remote handshake result; `max_batch_pages` comes from the server (PROTOCOL.md §4), clamped to 1..=32.
 */
export type ParseServiceHealth = { 
/**
 * u32 not u64: ts-rs maps u64 to bigint, and the frontend only displays this.
 */
pid: number | null, maxBatchPages: number, elapsedMs: number, 
/**
 * True when this is not a real handshake but the tolerated "the endpoint does not speak `/health`"
 * answer, whose figures are made up. The UI must not present them as the service's own — and for a
 * Mistral-shaped endpoint the batch size is a local setting, not something anyone advertised.
 */
synthetic: boolean, };
