// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PDFStatus } from "./PDFStatus";
import type { PageInfo } from "./PageInfo";

/**
 * Full PDF entity: identity fields + bound-JSON content.
 * bind = repo-relative bound-JSON path, None = unbound (legacy entry);
 * status/pages come from the bound JSON (Pending/empty when bind is None).
 */
export type PDF = { id: string, name: string, pdfPath: string, bind: string | null, status: PDFStatus, pages: Array<PageInfo>, };
