// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PDFStatus } from "./PDFStatus";
import type { PageInfo } from "./PageInfo";

/**
 * PDF entity; bind = repo-relative bound-JSON path (None = legacy/unbound → Pending, no pages).
 */
export type PDF = { id: string, name: string, pdfPath: string, bind: string | null, status: PDFStatus, pages: Array<PageInfo>, };
