// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Index entry (one line of the flat .ezrepo index):
 * id = stable identifier minted at import (survives moves/renames); name = PDF name;
 * bind = repo-relative bound-JSON path (None = unparsed); belong = logical folder label (None = root).
 */
export type PDFStruct = { id: string, name: string, bind: string | null, belong: string | null, };
