// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Book-level parse state; import creates Pending, the OCR pipeline drives the other two.
 */
export type PDFStatus = "Pending" | "Processing" | "Finished";
