// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One .ezrepo index line; id is minted at import; bind is the repo-relative bound-JSON path (None = unparsed); belong is a logical folder label (None = root).
 */
export type PDFStruct = { id: string, name: string, bind: string | null, belong: string | null, };
