// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 解析状态机（书级）：Pending 未开始处理 / Processing 处理中 / Finished 完成。
 * OCR 管线接入后维护后两态，当前导入即 Pending。
 */
export type PDFStatus = "Pending" | "Processing" | "Finished";
