// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 索引条目（.ezrepo 平铺索引的一行）：
 * id = 稳定唯一标识符（导入时生成，挪动/改名不变）；name = PDF 名；
 * bind = 结构 JSON 的仓库相对路径（None = 未解析）；belong = 所属顶层目录名（None = 根级）。
 */
export type PDFStruct = { id: string, name: string, bind: string | null, belong: string | null, };
