// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PDFStruct } from "./PDFStruct";

export type RepoTree = { folders: Array<string>, pdfs: Array<PDFStruct>, };
