// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 服务生命周期状态（前端「服务」灯数据源）；serde 序列化为小写
 */
export type ServiceStatus = "unknown" | "starting" | "connected" | "disconnected" | "failed";
