// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service lifecycle status (frontend "service" light source); serde serializes it as camelCase.
 */
export type ServiceStatus = "unknown" | "starting" | "connected" | "disconnected" | "failed";
