// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单元格：文本 + 横向跨列数（`<lcel>` 合并的结果）。纵向合并 v1 不表达。
 */
export type TableCell = { text: string, 
/**
 * 跨列数（≥1）；`<lcel>` 每出现一次 +1
 */
colspan: number, };
