// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRow } from "./TableRow";

/**
 * Table grid: `cols` is the slot count (a row's cell colspans sum to cols).
 */
export type TableGrid = { cols: number, rows: Array<TableRow>, };
