// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cell: text + horizontal colspan (from `<lcel>`). Vertical merges are not expressed in v1.
 */
export type TableCell = { text: string, 
/**
 * Colspan (≥1); +1 per `<lcel>`.
 */
colspan: number, };
