// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRow } from "./TableRow";

/**
 * 表格网格：`cols` 是列位数（各行真实单元格的 colspan 之和 = cols）
 */
export type TableGrid = { cols: number, rows: Array<TableRow>, };
