// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateInfo = { 
/**
 * Running app version (from tauri.conf).
 */
current: string, 
/**
 * Latest release tag without the `v` prefix; a missing release is an Err, not None.
 */
latest: string | null, newer: boolean, };
