// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 更新检查结果（前端 settings store 展示）
 */
export type UpdateInfo = { 
/**
 * 当前应用版本（tauri.conf 的 version）
 */
current: string, 
/**
 * 最新发布版本（tag 去掉 v 前缀）；无发布时应为 Err 而非 None
 */
latest: string | null, 
/**
 * 发布页地址（Releases 页面）
 */
url: string | null, 
/**
 * 是否有更新（语义化数字比较）
 */
newer: boolean, 
/**
 * 发布说明（截断）
 */
notes: string | null, };
